### PR TITLE
Fix path parameters with body for post put

### LINKED ISSUE #113: POST body cannot contain more than one body parameter
Swagger reports error "Operations must have no more than one body parameter". The swagger that is generated ends up having two parameters in the post request body and only one is allowed.

I added the following to the IStore.cs file

`        
[OperationContract]
[WebInvoke(Method = "POST")]
int BookTest(int id1, bool id2);
`

The swagger outputs the following:

`
"/v1/rest/BookTest":{"post":{"operationId":"SwaggerWcf.Test.Service.BookStore.BookTest","consumes":["application/json","application/xml"],"produces":["application/json","application/xml"],
"parameters":[
{"name":"id1","in":"body","required":true,"schema":{"type":"integer","format":"int32"}},{"name":"id2","in":"body","required":true,"schema":{"type":"boolean"}}],
"responses":{"default":{"description":"not available","schema":{"type":"integer","format":"int32"}}}}},
`

Expected:

`
 "/v1/rest/BookTest": {
      "post": {
        "operationId": "SwaggerWcf.Test.Service.BookStore.BookTest",
        "consumes": [
          "application/json",
          "application/xml"
        ],
        "produces": [
          "application/json",
          "application/xml"
        ],
        "parameters": [
          {
            "name": "BookTestBody",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SwaggerWcf.Test.Service.Data.BookTestBody"
            }
          }
        ],
        "responses": {
          "default": {
            "description": "not available",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        }
      }
    },
`

with BookTestBody definition:

`
"SwaggerWcf.Test.Service.Data.BookTestBody": {
      "properties": {
        "id1": {
          "type": "integer",
          "format": "int32"
        },
        "id2": {
          "type": "integer",
          "format": "int32"
        }
      }
    }
`

### PR DESCRIPTION
**Pull request by JFDionne**
For fix #113 and #138

### CODE REVIEW

File: src/SwaggerWcf/Support/Mapper.cs [hunk 1]
```diff
@@ -261,9 +261,17 @@ private static string ConcatPaths(string basePath, string pathUrl)
                     });
                 }
 
+                // parameters - body
+                int bodyParameterCount = 0;
+                foreach (ParameterInfo parameter in parameters)
```
Comment (HolisticDeveloper) [inline src/SwaggerWcf/Support/Mapper.cs]: Maybe replace this loop with a LINQ expression?

`int bodyParameterCount = parameters.Where(p => GetInType(uriTemplate, p.Name) == InType.Body).Count;`

Comment (JFDionne) [reply src/SwaggerWcf/Support/Mapper.cs]: Just did it.
